export default {
  SET_LEVELS: 'SET_LEVELS',
  SET_GAME_LEVEL: 'SET_GAME_LEVEL',
  SET_CURRENT_LEVEL: 'SET_CURRENT_LEVEL',
  SET_GAME_CHALLENGE: 'SET_GAME_CHALLENGE',
  UPDATE_CHALLENGE_STATUS: 'UPDATE_CHALLENGE_STATUS',
  UPDATE_LEVEL_STATUS: 'UPDATE_LEVEL_STATUS',
  UPDATE_USER_LIFE: 'UPDATE_USER_LIFE',
  RESET_LEVEL_STATE: 'RESET_LEVEL_STATE',
};
